# Generated by Django 3.1.5 on 2022-04-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEmpresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=150, verbose_name='Logo')),
                ('foto', models.CharField(max_length=150, verbose_name='Foto')),
                ('razao_social', models.CharField(max_length=45, verbose_name='Razão social')),
                ('email', models.EmailField(max_length=45, unique=True, verbose_name='E-mail')),
                ('senha_hash', models.CharField(max_length=64, verbose_name='Senha')),
                ('acessibilidade', models.CharField(blank=True, max_length=6, verbose_name='Acessibilidade')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Autenticado')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Login de Empresa',
                'verbose_name_plural': 'Login de Empresas',
                'db_table': 'login_empresa',
                'ordering': ['razao_social'],
            },
        ),
    ]
