# Generated by Django 3.1.5 on 2022-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto/associado', verbose_name='Foto')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=45, unique=True, verbose_name='E-mail')),
                ('senha_hash', models.CharField(max_length=64, verbose_name='Hash senha')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('numero', models.CharField(max_length=5, verbose_name='Número')),
                ('pcd', models.BooleanField(default=False, verbose_name='PCD')),
                ('outras_informacoes', models.TextField(blank=True, max_length=255, verbose_name='Outras informações')),
                ('instituicao_ensino', models.TextField(blank=True, max_length=255, verbose_name='Instituições de ensino')),
                ('curso_extra', models.TextField(blank=True, max_length=255, verbose_name='Cursos extras')),
                ('empresa_trabalhada', models.TextField(blank=True, max_length=255, verbose_name='Empresas trabalhadas')),
                ('cargo_ocupado', models.TextField(blank=True, max_length=255, verbose_name='Cargos ocupados')),
                ('laudo_medico', models.CharField(blank=True, max_length=255, verbose_name='Laudo médico')),
                ('acessibilidade', models.CharField(blank=True, max_length=6, verbose_name='Acessibilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Associado',
                'verbose_name_plural': 'Associados',
                'db_table': 'associado',
                'ordering': ['nome'],
            },
        ),
    ]
