# Generated by Django 3.1.5 on 2022-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto/admin', verbose_name='Foto')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('rf', models.CharField(max_length=8, unique=True, verbose_name='RF')),
                ('email', models.EmailField(max_length=45, unique=True, verbose_name='Email')),
                ('senha_hash', models.CharField(max_length=64, verbose_name='Hash senha')),
                ('acessibilidade', models.CharField(blank=True, max_length=6, verbose_name='Acessibilidade')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Autenticado')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
                'ordering': ['nome'],
            },
        ),
    ]
