# Generated by Django 3.1.5 on 2022-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/evento', verbose_name='Logo')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('url', models.URLField(max_length=100, verbose_name='URL')),
                ('data_exp', models.DateField(verbose_name='Data de expiração')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['titulo'],
            },
        ),
    ]
